name = "meccha-chameleon"
account_id = "faae494a756090f5f9c0ad7b8d1ddb88"
main = "src/worker.ts"
compatibility_date = "2026-07-18"
workers_dev = true

[assets]
directory = "./out"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = true

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "meccha-chameleon-data"
database_id = "28328a23-deca-4370-91c8-bad1a55a1254"
migrations_dir = "migrations"

[triggers]
crons = ["17 3 * * *"]
